import type { StockDef, SectorGroup } from './kr-stocks'

export type { StockDef, SectorGroup }

export const US_SECTORS: SectorGroup[] = [
  {
    sector: '빅테크',
    stocks: [
      { name: 'Apple', ticker: 'AAPL' },
      { name: 'Microsoft', ticker: 'MSFT' },
      { name: 'Google A', ticker: 'GOOGL' },
      { name: 'Google C', ticker: 'GOOG' },
      { name: 'Meta', ticker: 'META' },
      { name: 'Amazon', ticker: 'AMZN' },
      { name: 'Tesla', ticker: 'TSLA' },
    ],
  },
  {
    sector: '반도체/AI',
    stocks: [
      { name: 'NVIDIA', ticker: 'NVDA' },
      { name: 'AMD', ticker: 'AMD' },
      { name: 'Broadcom', ticker: 'AVGO' },
      { name: 'Qualcomm', ticker: 'QCOM' },
      { name: 'Texas Inst.', ticker: 'TXN' },
      { name: 'Micron', ticker: 'MU' },
      { name: 'SanDisk', ticker: 'SNDK' },
      { name: 'Intel', ticker: 'INTC' },
      { name: 'Applied Mat.', ticker: 'AMAT' },
      { name: 'Lam Research', ticker: 'LRCX' },
      { name: 'KLA', ticker: 'KLAC' },
      { name: 'Marvell', ticker: 'MRVL' },
      { name: 'ON Semi', ticker: 'ON' },
      { name: 'Microchip', ticker: 'MCHP' },
      { name: 'Analog Dev.', ticker: 'ADI' },
      { name: 'Monolithic', ticker: 'MPWR' },
    ],
  },
  {
    sector: '소프트웨어/클라우드',
    stocks: [
      { name: 'Oracle', ticker: 'ORCL' },
      { name: 'Salesforce', ticker: 'CRM' },
      { name: 'Adobe', ticker: 'ADBE' },
      { name: 'ServiceNow', ticker: 'NOW' },
      { name: 'Snowflake', ticker: 'SNOW' },
      { name: 'Palantir', ticker: 'PLTR' },
      { name: 'Workday', ticker: 'WDAY' },
      { name: 'Palo Alto', ticker: 'PANW' },
      { name: 'CrowdStrike', ticker: 'CRWD' },
      { name: 'Fortinet', ticker: 'FTNT' },
      { name: 'Datadog', ticker: 'DDOG' },
      { name: 'MongoDB', ticker: 'MDB' },
      { name: 'Cloudflare', ticker: 'NET' },
      { name: 'Zscaler', ticker: 'ZS' },
      { name: 'Intuit', ticker: 'INTU' },
      { name: 'Autodesk', ticker: 'ADSK' },
      { name: 'Synopsys', ticker: 'SNPS' },
      { name: 'Cadence', ticker: 'CDNS' },
    ],
  },
  {
    sector: '우주',
    stocks: [
      { name: 'SpaceX', ticker: 'SPCX' },
      { name: 'Rocket Lab', ticker: 'RKLB' },
      { name: 'Planet Labs', ticker: 'PL' },
      { name: 'Iridium', ticker: 'IRDM' },
      { name: 'Redwire', ticker: 'RDW' },
      { name: 'AST SpaceMobile', ticker: 'ASTS' },
      { name: 'Intuitive Mach.', ticker: 'LUNR' },
      { name: 'Viasat', ticker: 'VSAT' },
      { name: 'BlackSky', ticker: 'BKSY' },
    ],
  },
  {
    sector: '인터넷/플랫폼',
    stocks: [
      { name: 'Netflix', ticker: 'NFLX' },
      { name: 'Uber', ticker: 'UBER' },
      { name: 'Airbnb', ticker: 'ABNB' },
      { name: 'Booking', ticker: 'BKNG' },
      { name: 'Spotify', ticker: 'SPOT' },
      { name: 'DoorDash', ticker: 'DASH' },
      { name: 'Lyft', ticker: 'LYFT' },
      { name: 'Pinterest', ticker: 'PINS' },
      { name: 'Snap', ticker: 'SNAP' },
      { name: 'Reddit', ticker: 'RDDT' },
    ],
  },
  {
    sector: '전자/하드웨어',
    stocks: [
      { name: 'Dell', ticker: 'DELL' },
      { name: 'HP', ticker: 'HPQ' },
      { name: 'Seagate', ticker: 'STX' },
      { name: 'Western Dig.', ticker: 'WDC' },
      { name: 'Super Micro', ticker: 'SMCI' },
      { name: 'Corning', ticker: 'GLW' },
      { name: 'Zebra Tech', ticker: 'ZBRA' },
    ],
  },
  {
    sector: '금융/은행',
    stocks: [
      { name: 'JPMorgan', ticker: 'JPM' },
      { name: 'BofA', ticker: 'BAC' },
      { name: 'Goldman', ticker: 'GS' },
      { name: 'Morgan Stly', ticker: 'MS' },
      { name: 'Wells Fargo', ticker: 'WFC' },
      { name: 'Citigroup', ticker: 'C' },
      { name: 'Berkshire', ticker: 'BRK-B' },
      { name: 'Schwab', ticker: 'SCHW' },
      { name: 'BlackRock', ticker: 'BLK' },
      { name: 'U.S. Bancorp', ticker: 'USB' },
      { name: 'PNC', ticker: 'PNC' },
      { name: 'Truist', ticker: 'TFC' },
    ],
  },
  {
    sector: '결제/핀테크',
    stocks: [
      { name: 'Visa', ticker: 'V' },
      { name: 'Mastercard', ticker: 'MA' },
      { name: 'Amex', ticker: 'AXP' },
      { name: 'PayPal', ticker: 'PYPL' },
      { name: 'Capital One', ticker: 'COF' },
      { name: 'Fiserv', ticker: 'FI' },
      { name: 'FIS', ticker: 'FIS' },
      { name: 'FleetCor', ticker: 'FLT' },
    ],
  },
  {
    sector: '헬스케어',
    stocks: [
      { name: 'UnitedHealth', ticker: 'UNH' },
      { name: 'Eli Lilly', ticker: 'LLY' },
      { name: 'J&J', ticker: 'JNJ' },
      { name: 'AbbVie', ticker: 'ABBV' },
      { name: 'Merck', ticker: 'MRK' },
      { name: 'Pfizer', ticker: 'PFE' },
      { name: 'Amgen', ticker: 'AMGN' },
      { name: 'Thermo Fisher', ticker: 'TMO' },
      { name: 'Abbott', ticker: 'ABT' },
      { name: 'Intuitive Surg', ticker: 'ISRG' },
      { name: 'Danaher', ticker: 'DHR' },
      { name: 'Boston Sci.', ticker: 'BSX' },
      { name: 'Cigna', ticker: 'CI' },
      { name: 'CVS Health', ticker: 'CVS' },
      { name: 'Elevance', ticker: 'ELV' },
      { name: 'Regeneron', ticker: 'REGN' },
      { name: 'Vertex', ticker: 'VRTX' },
      { name: 'Gilead', ticker: 'GILD' },
      { name: 'Biogen', ticker: 'BIIB' },
      { name: 'Moderna', ticker: 'MRNA' },
    ],
  },
  {
    sector: '에너지',
    stocks: [
      { name: 'ExxonMobil', ticker: 'XOM' },
      { name: 'Chevron', ticker: 'CVX' },
      { name: 'ConocoPhil.', ticker: 'COP' },
      { name: 'Schlumberger', ticker: 'SLB' },
      { name: 'EOG Res.', ticker: 'EOG' },
      { name: 'Marathon Pete.', ticker: 'MPC' },
      { name: 'Phillips 66', ticker: 'PSX' },
      { name: 'Valero', ticker: 'VLO' },
      { name: 'Hess', ticker: 'HES' },
      { name: 'Fluence Energy', ticker: 'FLNC' },
    ],
  },
  {
    sector: '전력/그리드',
    stocks: [
      { name: 'Vistra', ticker: 'VST' },
      { name: 'Constellation', ticker: 'CEG' },
      { name: 'GE Vernova', ticker: 'GEV' },
      { name: 'Quanta Svc', ticker: 'PWR' },
      { name: 'Eaton', ticker: 'ETN' },
      { name: 'Hubbell', ticker: 'HUBB' },
      { name: 'Vertiv', ticker: 'VRT' },
      { name: 'AECOM', ticker: 'ACM' },
      { name: 'MYR Group', ticker: 'MYRG' },
      { name: 'IES Holdings', ticker: 'IESC' },
      { name: 'Comfort Sys.', ticker: 'FIX' },
      { name: 'Willscot', ticker: 'WSC' },
    ],
  },
  {
    sector: '신재생에너지',
    stocks: [
      { name: 'First Solar', ticker: 'FSLR' },
      { name: 'Enphase', ticker: 'ENPH' },
      { name: 'SolarEdge', ticker: 'SEDG' },
      { name: 'Sunrun', ticker: 'RUN' },
      { name: 'Array Tech.', ticker: 'ARRY' },
      { name: 'NEXTracker', ticker: 'NXT' },
      { name: 'Sunnova', ticker: 'NOVA' },
      { name: 'TPI Composites', ticker: 'TPIC' },
      { name: 'Plug Power', ticker: 'PLUG' },
      { name: 'Bloom Energy', ticker: 'BE' },
      { name: 'FuelCell', ticker: 'FCEL' },
      { name: 'Clearway Energy', ticker: 'CWEN' },
    ],
  },
  {
    sector: '원자재',
    stocks: [
      { name: '금 ETF', ticker: 'GLD' },
      { name: '금광 ETF', ticker: 'GDX' },
      { name: 'Newmont', ticker: 'NEM' },
      { name: 'Barrick Gold', ticker: 'GOLD' },
      { name: '리튬 ETF', ticker: 'LIT' },
      { name: 'Albemarle', ticker: 'ALB' },
      { name: 'SQM', ticker: 'SQM' },
      { name: 'Freeport', ticker: 'FCX' },
      { name: 'Air Products', ticker: 'APD' },
      { name: 'Linde', ticker: 'LIN' },
      { name: 'Nucor', ticker: 'NUE' },
    ],
  },
  {
    sector: '소비재',
    stocks: [
      { name: 'Walmart', ticker: 'WMT' },
      { name: 'Costco', ticker: 'COST' },
      { name: 'Home Depot', ticker: 'HD' },
      { name: "McDonald's", ticker: 'MCD' },
      { name: 'Nike', ticker: 'NKE' },
      { name: 'Starbucks', ticker: 'SBUX' },
      { name: 'Target', ticker: 'TGT' },
      { name: "Lowe's", ticker: 'LOW' },
      { name: 'TJX', ticker: 'TJX' },
      { name: "Macy's", ticker: 'M' },
      { name: 'Dollar General', ticker: 'DG' },
      { name: 'Ross Stores', ticker: 'ROST' },
      { name: 'O\'Reilly Auto', ticker: 'ORLY' },
      { name: 'AutoZone', ticker: 'AZO' },
    ],
  },
  {
    sector: '필수소비재',
    stocks: [
      { name: 'P&G', ticker: 'PG' },
      { name: 'Coca-Cola', ticker: 'KO' },
      { name: 'PepsiCo', ticker: 'PEP' },
      { name: 'Philip Morris', ticker: 'PM' },
      { name: 'Altria', ticker: 'MO' },
      { name: 'Colgate', ticker: 'CL' },
      { name: 'Mondelez', ticker: 'MDLZ' },
      { name: 'Kraft Heinz', ticker: 'KHC' },
      { name: 'Kimberly-Clark', ticker: 'KMB' },
    ],
  },
  {
    sector: '산업/기계',
    stocks: [
      { name: 'GE Aerospace', ticker: 'GE' },
      { name: 'Caterpillar', ticker: 'CAT' },
      { name: 'Honeywell', ticker: 'HON' },
      { name: 'Deere', ticker: 'DE' },
      { name: 'Eaton', ticker: 'ETN' },
      { name: 'Emerson', ticker: 'EMR' },
      { name: 'Union Pacific', ticker: 'UNP' },
      { name: 'FedEx', ticker: 'FDX' },
      { name: 'UPS', ticker: 'UPS' },
      { name: 'CSX', ticker: 'CSX' },
      { name: 'Norfolk South.', ticker: 'NSC' },
      { name: 'Parker Hannifin', ticker: 'PH' },
      { name: 'Illinois Tool', ticker: 'ITW' },
      { name: '3M', ticker: 'MMM' },
    ],
  },
  {
    sector: '방산',
    stocks: [
      { name: 'RTX', ticker: 'RTX' },
      { name: 'Lockheed', ticker: 'LMT' },
      { name: 'Northrop', ticker: 'NOC' },
      { name: 'Boeing', ticker: 'BA' },
      { name: 'Gen. Dynamics', ticker: 'GD' },
      { name: 'L3Harris', ticker: 'LHX' },
      { name: 'TransDigm', ticker: 'TDG' },
    ],
  },
  {
    sector: '통신/미디어',
    stocks: [
      { name: 'T-Mobile', ticker: 'TMUS' },
      { name: 'AT&T', ticker: 'T' },
      { name: 'Verizon', ticker: 'VZ' },
      { name: 'Disney', ticker: 'DIS' },
      { name: 'Comcast', ticker: 'CMCSA' },
      { name: 'Warner Bros.', ticker: 'WBD' },
      { name: 'Fox', ticker: 'FOXA' },
      { name: 'Charter', ticker: 'CHTR' },
    ],
  },
  {
    sector: '부동산',
    stocks: [
      { name: 'American Tower', ticker: 'AMT' },
      { name: 'Prologis', ticker: 'PLD' },
      { name: 'Equinix', ticker: 'EQIX' },
      { name: 'Simon Prop.', ticker: 'SPG' },
      { name: 'Crown Castle', ticker: 'CCI' },
      { name: 'Public Storage', ticker: 'PSA' },
      { name: 'Realty Income', ticker: 'O' },
      { name: 'CBRE', ticker: 'CBRE' },
    ],
  },
  {
    sector: '유틸리티',
    stocks: [
      { name: 'NextEra', ticker: 'NEE' },
      { name: 'Duke Energy', ticker: 'DUK' },
      { name: 'Southern Co.', ticker: 'SO' },
      { name: 'Dominion', ticker: 'D' },
      { name: 'American Elec.', ticker: 'AEP' },
      { name: 'Sempra', ticker: 'SRE' },
    ],
  },
]

export const ALL_US_TICKERS = US_SECTORS.flatMap((s) =>
  s.stocks.map((st) => st.ticker)
)
